### ISSUE TITLE
[1.12.2] The Condition Overload Modifier stops damage boosting traits from working.

### ISSUE THREAD

**Issue by SonicX8000** [UvMidnight/Condition-Overload#1]
Minecraft: 1.12.2
Forge: 14.23.5.2860

Mods: 4
conditionoverload-1.1.0
jei_1.12.2-4.16.1.302
Mantle-1.12-1.3.3.55
TConstruct-1.12.2-2.13.0.183

---

I wish I would've caught this sooner back when it was being tested, but it's only until today that I noticed that this modifier will cancel out all damage boosting trait effects.

Cold-Blooded will no longer apply it's 50% damage boost for mobs with full health, Insatiable no longer steadily ups the damage done when attacking mobs. Jagged's Damage Bonus gets canceled out.

For a test I used an iron Golem since it has 100 Health, and I've used an all Manyullyn Broadsword, one with the modifier and one without the modifier. Toro HUD is used here in order to view the damage pop-offs, although it tends to round up the damage.

Manyullyn Broadsword, 10.72 Base Damage
Cold-Blooded + Insatiable
16, 11, 11, 12, 12, 12, 13, 13...

This appears to be fine. The first hit got boosted and then steadily went up due to Insatiable applying a boost.

=====

Prismarine Broadsword, 97. Base Damage (+2.03 Jagged Boost)
Fractured + Jagged + Aquadynamic + Lightweight
12, 12, 12, 12, 12, 12, 12, 12, 12...

Looks normal.

---

Now to apply the modifier...

Manyullyn Broadsword, 10.72 Base Damage
Cold-Blooded + Insatiable + Condition Overload modifier
11, 11, 11, 11, 11, 11, 11, 11, 11, 11...

This shows that Cold-Blooded didn't apply it's damage boost, as well as no increase to damage with Insatiable.

=====

Prismarine Broadsword, 97. Base Damage (+2.12 Jagged Boost)
Fractured + Jagged + Aquadynamic + Lightweight + Condition Overload modifier
10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10...

This shows that Jagged's Damage Bonus was canceled, and instead dealing the base damage.

**Comment by UvMidnight** [comment]
Going to look into fixing it today.

**Comment by UvMidnight** [comment]
Resolved by e02332b
